#!/bin/bash

echo "🔧 Vercel環境変数セットアップ"
echo "================================"
echo ""
echo "以下のコマンドを実行して、Vercelに環境変数を設定してください："
echo ""
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL"
echo "→ 値: https://pjfspvwwzaemfmeizvhl.supabase.co"
echo ""
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "→ 値: [Supabaseダッシュボードから新しいキーを取得]"
echo ""
echo "vercel env add NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "→ 値: pk_test_51QfeBWP22JLKj0kaCY9v4fI0VJ3xbOp0bP1XyOVFJWjVKmDv6u5GvCRlRdxQ12IBVZS6w3cpRxgC3wKoeCcKf1lQ00rr0BNCUA"
echo ""
echo "vercel env add STRIPE_PRICE_SENIOR_AGENT"
echo "→ 値: price_1QfeDmP22JLKj0kaL1nNGnAk"
echo ""
echo "vercel env add NEXT_PUBLIC_FEEDBACK_LINE_URL"
echo "→ 値: https://line.me/ti/g2/DsmrFz_36bh5BDMJ80DpDtNQ-0fjGDKx_cdoCg?utm_source=invitation&utm_medium=link_copy&utm_campaign=default"
echo ""
echo "================================"
echo "✅ すべて設定したら 'vercel --prod' で再デプロイ"

